name: build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Enter name of tag'
        required: false
        default: ''

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: build release
      run: cargo build --verbose --release

    - name: build debug
      run: cargo build --verbose
      
    - name: tests
      run: cargo test --verbose

    - name: copy paste
      run: |
        cp target/release/mcstatus-rust.exe mcstatus-release.exe
        cp target/debug/mcstatus-rust.exe mcstatus-debug.exe

    - name: create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        files: |
          mcstatus-release.exe
          mcstatus-debug.exe
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}