name: build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: build release
      run: cargo build --verbose --release

    - name: build debug
      run: cargo build --verbose
      
    - name: tests
      run: cargo test --verbose

    - name: create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/mcstatus-rust.exe
          target/debug/mcstatus-rust.exe
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
